-- Auto-generated by sql/generate_init_database_sql.py
SET NAMES utf8mb4;
DROP DATABASE IF EXISTS `secmgmt_db`;
CREATE DATABASE IF NOT EXISTS `secmgmt_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `secmgmt_db`;


CREATE TABLE device_operation_log (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	device_type VARCHAR(30) NOT NULL, 
	device_id INTEGER NOT NULL, 
	action VARCHAR(50) NOT NULL, 
	operator_id INTEGER, 
	operator_name VARCHAR(50), 
	detail TEXT, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id)
);
CREATE INDEX ix_device_operation_log_device_id ON device_operation_log (device_id);
CREATE INDEX ix_device_operation_log_device_type ON device_operation_log (device_type);


CREATE TABLE device_status_log (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	device_type VARCHAR(30) NOT NULL, 
	device_id INTEGER NOT NULL, 
	old_status VARCHAR(20), 
	new_status VARCHAR(20) NOT NULL, 
	message TEXT, 
	checked_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id)
);
CREATE INDEX ix_device_status_log_checked_at ON device_status_log (checked_at);
CREATE INDEX ix_device_status_log_device_id ON device_status_log (device_id);
CREATE INDEX ix_device_status_log_device_type ON device_status_log (device_type);
CREATE INDEX ix_device_status_log_new_status ON device_status_log (new_status);


CREATE TABLE operation_log (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	trace_id VARCHAR(64), 
	source VARCHAR(20) NOT NULL, 
	operator_id INTEGER, 
	operator_username VARCHAR(50), 
	operator_real_name VARCHAR(50), 
	role_codes VARCHAR(255), 
	role_names VARCHAR(255), 
	client_ip VARCHAR(64), 
	ip_location VARCHAR(120), 
	user_agent TEXT, 
	os_name VARCHAR(50), 
	menu_code VARCHAR(100), 
	menu_name VARCHAR(150), 
	route_path VARCHAR(255), 
	page_title VARCHAR(150), 
	page_component VARCHAR(100), 
	action_code VARCHAR(150), 
	action_name VARCHAR(150), 
	operation_type VARCHAR(80), 
	object_type VARCHAR(80), 
	object_id VARCHAR(100), 
	object_name VARCHAR(255), 
	object_location VARCHAR(255), 
	request_method VARCHAR(10), 
	request_path VARCHAR(255), 
	request_query TEXT, 
	request_params LONGTEXT, 
	device_point_info LONGTEXT, 
	before_snapshot LONGTEXT, 
	after_snapshot LONGTEXT, 
	error_stack LONGTEXT, 
	result_status VARCHAR(20), 
	response_status INTEGER NOT NULL, 
	duration_ms BIGINT NOT NULL, 
	storage_partition VARCHAR(32) NOT NULL, 
	retention_days INTEGER NOT NULL, 
	extra_json LONGTEXT, 
	operation_time DATETIME(3) NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id)
);
CREATE INDEX ix_operation_log_action_code ON operation_log (action_code);
CREATE INDEX ix_operation_log_menu_code ON operation_log (menu_code);
CREATE INDEX ix_operation_log_object_type ON operation_log (object_type);
CREATE INDEX ix_operation_log_operation_time ON operation_log (operation_time);
CREATE INDEX ix_operation_log_operation_type ON operation_log (operation_type);
CREATE INDEX ix_operation_log_operator_username ON operation_log (operator_username);
CREATE INDEX ix_operation_log_result_status ON operation_log (result_status);
CREATE INDEX ix_operation_log_storage_partition ON operation_log (storage_partition);
CREATE INDEX ix_operation_log_trace_id ON operation_log (trace_id);


CREATE TABLE factory_area (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	factory_code VARCHAR(50) NOT NULL, 
	factory_name VARCHAR(100) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	remark VARCHAR(255), 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_factory_area_factory_code ON factory_area (factory_code);


CREATE TABLE push_config (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	config_name VARCHAR(100) NOT NULL, 
	provider_type VARCHAR(30) NOT NULL, 
	webhook VARCHAR(500) NOT NULL, 
	secret_encrypted TEXT, 
	app_id VARCHAR(120), 
	app_secret_encrypted TEXT, 
	template_id VARCHAR(120), 
	receiver_open_ids_json TEXT NOT NULL, 
	factory_ids_json TEXT NOT NULL, 
	zone_ids_json TEXT NOT NULL, 
	alarm_types_json TEXT NOT NULL, 
	alarm_levels_json TEXT NOT NULL, 
	active_time_ranges_json TEXT NOT NULL, 
	enabled BOOL NOT NULL, 
	rate_limit_window_seconds INTEGER NOT NULL, 
	rate_limit_max_count INTEGER NOT NULL, 
	retry_max_count INTEGER NOT NULL, 
	retry_interval_seconds INTEGER NOT NULL, 
	remark TEXT, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_push_config_config_name ON push_config (config_name);
CREATE INDEX ix_push_config_enabled ON push_config (enabled);
CREATE INDEX ix_push_config_provider_type ON push_config (provider_type);


CREATE TABLE system_setting (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	setting_key VARCHAR(120) NOT NULL, 
	setting_name VARCHAR(150) NOT NULL, 
	setting_value VARCHAR(255) NOT NULL, 
	remark VARCHAR(255), 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_system_setting_setting_key ON system_setting (setting_key);


CREATE TABLE smart_interface_capability (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	capability_code VARCHAR(60) NOT NULL, 
	capability_name VARCHAR(100) NOT NULL, 
	event_category VARCHAR(40) NOT NULL, 
	supports_push BOOL NOT NULL, 
	supports_pull BOOL NOT NULL, 
	supports_ai_review BOOL NOT NULL, 
	payload_schema_json TEXT, 
	default_rule_json TEXT, 
	enabled BOOL NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_smart_interface_capability_capability_code ON smart_interface_capability (capability_code);
CREATE INDEX ix_smart_interface_capability_enabled ON smart_interface_capability (enabled);


CREATE TABLE smart_interface_provider (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	provider_code VARCHAR(60) NOT NULL, 
	provider_name VARCHAR(100) NOT NULL, 
	provider_type VARCHAR(40) NOT NULL, 
	auth_type VARCHAR(40) NOT NULL, 
	base_url VARCHAR(255), 
	callback_path VARCHAR(255), 
	secret_encrypted TEXT, 
	config_schema_json TEXT, 
	enabled BOOL NOT NULL, 
	remark VARCHAR(255), 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id)
);
CREATE INDEX ix_smart_interface_provider_enabled ON smart_interface_provider (enabled);
CREATE UNIQUE INDEX ix_smart_interface_provider_provider_code ON smart_interface_provider (provider_code);
CREATE INDEX ix_smart_interface_provider_provider_type ON smart_interface_provider (provider_type);


CREATE TABLE sys_dict_type (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	dict_code VARCHAR(60) NOT NULL, 
	dict_name VARCHAR(100) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	remark VARCHAR(255), 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_sys_dict_type_dict_code ON sys_dict_type (dict_code);


CREATE TABLE sys_menu (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(50) NOT NULL, 
	code VARCHAR(60) NOT NULL, 
	parent_id INTEGER, 
	route_name VARCHAR(100), 
	route_path VARCHAR(120), 
	icon VARCHAR(20), 
	menu_type VARCHAR(20) NOT NULL, 
	sort INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(parent_id) REFERENCES sys_menu (id)
);
CREATE UNIQUE INDEX ix_sys_menu_code ON sys_menu (code);


CREATE TABLE sys_permission (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(50) NOT NULL, 
	code VARCHAR(80) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	remark TEXT, 
	is_button BOOL NOT NULL, 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_sys_permission_code ON sys_permission (code);


CREATE TABLE sys_role (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	role_code VARCHAR(50) NOT NULL, 
	role_name VARCHAR(50) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	remark VARCHAR(255), 
	data_scope_type VARCHAR(30) NOT NULL, 
	data_scope_value VARCHAR(255), 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_sys_role_role_code ON sys_role (role_code);


CREATE TABLE factory_zone (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	factory_id INTEGER NOT NULL, 
	zone_code VARCHAR(50) NOT NULL, 
	zone_name VARCHAR(100) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	remark VARCHAR(255), 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_factory_zone_code UNIQUE (factory_id, zone_code), 
	FOREIGN KEY(factory_id) REFERENCES factory_area (id)
);
CREATE INDEX ix_factory_zone_factory_id ON factory_zone (factory_id);


CREATE TABLE recorder_device (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	device_code VARCHAR(60) NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	ip VARCHAR(64) NOT NULL, 
	sdk_port INTEGER NOT NULL, 
	http_port INTEGER NOT NULL, 
	username VARCHAR(50) NOT NULL, 
	password_encrypted TEXT NOT NULL, 
	channel_count INTEGER NOT NULL, 
	factory_id INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	last_online_at DATETIME, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(factory_id) REFERENCES factory_area (id)
);
CREATE UNIQUE INDEX ix_recorder_device_device_code ON recorder_device (device_code);
CREATE INDEX ix_recorder_device_factory_id ON recorder_device (factory_id);
CREATE INDEX ix_recorder_device_ip ON recorder_device (ip);


CREATE TABLE smart_device_binding (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	provider_id INTEGER NOT NULL, 
	capability_id INTEGER NOT NULL, 
	source_type VARCHAR(20) NOT NULL, 
	source_id INTEGER NOT NULL, 
	enabled BOOL NOT NULL, 
	priority INTEGER NOT NULL, 
	connection_config_json TEXT, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_smart_device_binding UNIQUE (provider_id, capability_id, source_type, source_id), 
	FOREIGN KEY(provider_id) REFERENCES smart_interface_provider (id), 
	FOREIGN KEY(capability_id) REFERENCES smart_interface_capability (id)
);
CREATE INDEX ix_smart_device_binding_capability_id ON smart_device_binding (capability_id);
CREATE INDEX ix_smart_device_binding_enabled ON smart_device_binding (enabled);
CREATE INDEX ix_smart_device_binding_provider_id ON smart_device_binding (provider_id);
CREATE INDEX ix_smart_device_binding_source_id ON smart_device_binding (source_id);
CREATE INDEX ix_smart_device_binding_source_type ON smart_device_binding (source_type);


CREATE TABLE sys_dict_item (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	dict_type_id INTEGER NOT NULL, 
	item_label VARCHAR(100) NOT NULL, 
	item_value VARCHAR(100) NOT NULL, 
	item_sort INTEGER NOT NULL, 
	is_default BOOL NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	remark TEXT, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_dict_item_value UNIQUE (dict_type_id, item_value), 
	FOREIGN KEY(dict_type_id) REFERENCES sys_dict_type (id)
);
CREATE INDEX ix_sys_dict_item_dict_type_id ON sys_dict_item (dict_type_id);


CREATE TABLE sys_role_menu (
	role_id INTEGER NOT NULL, 
	menu_id INTEGER NOT NULL, 
	PRIMARY KEY (role_id, menu_id), 
	FOREIGN KEY(role_id) REFERENCES sys_role (id), 
	FOREIGN KEY(menu_id) REFERENCES sys_menu (id)
);


CREATE TABLE sys_role_permission (
	role_id INTEGER NOT NULL, 
	permission_id INTEGER NOT NULL, 
	PRIMARY KEY (role_id, permission_id), 
	FOREIGN KEY(role_id) REFERENCES sys_role (id), 
	FOREIGN KEY(permission_id) REFERENCES sys_permission (id)
);


CREATE TABLE camera_device (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	device_code VARCHAR(60) NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	ip VARCHAR(64) NOT NULL, 
	sdk_port INTEGER NOT NULL, 
	http_port INTEGER NOT NULL, 
	rtsp_port INTEGER NOT NULL, 
	username VARCHAR(50) NOT NULL, 
	password_encrypted TEXT NOT NULL, 
	factory_id INTEGER NOT NULL, 
	zone_id INTEGER NOT NULL, 
	install_location VARCHAR(255), 
	support_ai BOOL NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	last_online_at DATETIME, 
	remark VARCHAR(255), 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(factory_id) REFERENCES factory_area (id), 
	FOREIGN KEY(zone_id) REFERENCES factory_zone (id)
);
CREATE UNIQUE INDEX ix_camera_device_device_code ON camera_device (device_code);
CREATE INDEX ix_camera_device_factory_id ON camera_device (factory_id);
CREATE INDEX ix_camera_device_ip ON camera_device (ip);
CREATE INDEX ix_camera_device_zone_id ON camera_device (zone_id);


CREATE TABLE smart_binding_rule (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	binding_id INTEGER NOT NULL, 
	rule_name VARCHAR(100) NOT NULL, 
	enabled BOOL NOT NULL, 
	alarm_enabled BOOL NOT NULL, 
	alarm_level VARCHAR(20) NOT NULL, 
	dedup_window_seconds INTEGER NOT NULL, 
	cooldown_seconds INTEGER NOT NULL, 
	min_confidence FLOAT, 
	active_time_plan_json TEXT, 
	snapshot_enabled BOOL NOT NULL, 
	record_clip_enabled BOOL NOT NULL, 
	record_pre_seconds INTEGER NOT NULL, 
	record_post_seconds INTEGER NOT NULL, 
	push_enabled BOOL NOT NULL, 
	push_channels_json TEXT, 
	send_to_ai BOOL NOT NULL, 
	ai_flow_code VARCHAR(60), 
	generate_alarm_directly BOOL NOT NULL, 
	remark VARCHAR(255), 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(binding_id) REFERENCES smart_device_binding (id)
);
CREATE INDEX ix_smart_binding_rule_binding_id ON smart_binding_rule (binding_id);
CREATE INDEX ix_smart_binding_rule_enabled ON smart_binding_rule (enabled);


CREATE TABLE smart_raw_event (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	provider_id INTEGER NOT NULL, 
	capability_id INTEGER, 
	binding_id INTEGER, 
	source_type VARCHAR(20), 
	source_id INTEGER, 
	source_event_id VARCHAR(100), 
	event_no VARCHAR(64) NOT NULL, 
	event_time DATETIME NOT NULL, 
	signature_valid BOOL, 
	headers_json TEXT, 
	raw_payload_json TEXT NOT NULL, 
	parse_status VARCHAR(20) NOT NULL, 
	parse_error TEXT, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(provider_id) REFERENCES smart_interface_provider (id), 
	FOREIGN KEY(capability_id) REFERENCES smart_interface_capability (id), 
	FOREIGN KEY(binding_id) REFERENCES smart_device_binding (id)
);
CREATE INDEX ix_smart_raw_event_binding_id ON smart_raw_event (binding_id);
CREATE INDEX ix_smart_raw_event_capability_id ON smart_raw_event (capability_id);
CREATE UNIQUE INDEX ix_smart_raw_event_event_no ON smart_raw_event (event_no);
CREATE INDEX ix_smart_raw_event_event_time ON smart_raw_event (event_time);
CREATE INDEX ix_smart_raw_event_parse_status ON smart_raw_event (parse_status);
CREATE INDEX ix_smart_raw_event_provider_id ON smart_raw_event (provider_id);
CREATE INDEX ix_smart_raw_event_source_event_id ON smart_raw_event (source_event_id);
CREATE INDEX ix_smart_raw_event_source_id ON smart_raw_event (source_id);
CREATE INDEX ix_smart_raw_event_source_type ON smart_raw_event (source_type);


CREATE TABLE sys_dept (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	dept_code VARCHAR(50) NOT NULL, 
	dept_name VARCHAR(100) NOT NULL, 
	parent_id INTEGER, 
	factory_id INTEGER, 
	zone_id INTEGER, 
	leader VARCHAR(50), 
	phone VARCHAR(30), 
	sort INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	remark VARCHAR(255), 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(parent_id) REFERENCES sys_dept (id), 
	FOREIGN KEY(factory_id) REFERENCES factory_area (id), 
	FOREIGN KEY(zone_id) REFERENCES factory_zone (id)
);
CREATE UNIQUE INDEX ix_sys_dept_dept_code ON sys_dept (dept_code);
CREATE INDEX ix_sys_dept_factory_id ON sys_dept (factory_id);
CREATE INDEX ix_sys_dept_zone_id ON sys_dept (zone_id);


CREATE TABLE recorder_channel (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	recorder_id INTEGER NOT NULL, 
	channel_no INTEGER NOT NULL, 
	name VARCHAR(100) NOT NULL, 
	camera_id INTEGER, 
	factory_id INTEGER NOT NULL, 
	zone_id INTEGER, 
	enabled BOOL NOT NULL, 
	support_playback BOOL NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_recorder_channel_no UNIQUE (recorder_id, channel_no), 
	FOREIGN KEY(recorder_id) REFERENCES recorder_device (id), 
	FOREIGN KEY(camera_id) REFERENCES camera_device (id), 
	FOREIGN KEY(factory_id) REFERENCES factory_area (id), 
	FOREIGN KEY(zone_id) REFERENCES factory_zone (id)
);
CREATE INDEX ix_recorder_channel_camera_id ON recorder_channel (camera_id);
CREATE INDEX ix_recorder_channel_factory_id ON recorder_channel (factory_id);
CREATE INDEX ix_recorder_channel_recorder_id ON recorder_channel (recorder_id);
CREATE INDEX ix_recorder_channel_zone_id ON recorder_channel (zone_id);


CREATE TABLE sys_user (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	username VARCHAR(50) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	real_name VARCHAR(50) NOT NULL, 
	dept_id INTEGER, 
	status VARCHAR(20) NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(dept_id) REFERENCES sys_dept (id)
);
CREATE INDEX ix_sys_user_dept_id ON sys_user (dept_id);
CREATE UNIQUE INDEX ix_sys_user_username ON sys_user (username);


CREATE TABLE ai_event (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	event_no VARCHAR(64) NOT NULL, 
	source_type VARCHAR(40) NOT NULL, 
	event_type VARCHAR(60) NOT NULL, 
	event_level VARCHAR(20) NOT NULL, 
	event_time DATETIME NOT NULL, 
	camera_id INTEGER, 
	recorder_id INTEGER, 
	channel_id INTEGER, 
	factory_id INTEGER, 
	zone_id INTEGER, 
	image_url VARCHAR(500), 
	video_url VARCHAR(500), 
	confidence FLOAT, 
	raw_json TEXT NOT NULL, 
	dedup_key VARCHAR(200) NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(camera_id) REFERENCES camera_device (id), 
	FOREIGN KEY(recorder_id) REFERENCES recorder_device (id), 
	FOREIGN KEY(channel_id) REFERENCES recorder_channel (id), 
	FOREIGN KEY(factory_id) REFERENCES factory_area (id), 
	FOREIGN KEY(zone_id) REFERENCES factory_zone (id)
);
CREATE INDEX ix_ai_event_camera_id ON ai_event (camera_id);
CREATE INDEX ix_ai_event_channel_id ON ai_event (channel_id);
CREATE INDEX ix_ai_event_dedup_key ON ai_event (dedup_key);
CREATE INDEX ix_ai_event_event_level ON ai_event (event_level);
CREATE UNIQUE INDEX ix_ai_event_event_no ON ai_event (event_no);
CREATE INDEX ix_ai_event_event_time ON ai_event (event_time);
CREATE INDEX ix_ai_event_event_type ON ai_event (event_type);
CREATE INDEX ix_ai_event_factory_id ON ai_event (factory_id);
CREATE INDEX ix_ai_event_recorder_id ON ai_event (recorder_id);
CREATE INDEX ix_ai_event_source_type ON ai_event (source_type);
CREATE INDEX ix_ai_event_zone_id ON ai_event (zone_id);


CREATE TABLE smart_event (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	raw_event_id INTEGER, 
	binding_id INTEGER, 
	provider_id INTEGER NOT NULL, 
	capability_id INTEGER, 
	event_code VARCHAR(64) NOT NULL, 
	event_type VARCHAR(60) NOT NULL, 
	event_level VARCHAR(20) NOT NULL, 
	source_stage VARCHAR(20) NOT NULL, 
	event_time DATETIME NOT NULL, 
	camera_id INTEGER, 
	recorder_id INTEGER, 
	channel_id INTEGER, 
	factory_id INTEGER, 
	zone_id INTEGER, 
	image_url VARCHAR(500), 
	video_url VARCHAR(500), 
	confidence FLOAT, 
	dedup_key VARCHAR(200) NOT NULL, 
	normalized_payload_json TEXT NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(raw_event_id) REFERENCES smart_raw_event (id), 
	FOREIGN KEY(binding_id) REFERENCES smart_device_binding (id), 
	FOREIGN KEY(provider_id) REFERENCES smart_interface_provider (id), 
	FOREIGN KEY(capability_id) REFERENCES smart_interface_capability (id), 
	FOREIGN KEY(camera_id) REFERENCES camera_device (id), 
	FOREIGN KEY(recorder_id) REFERENCES recorder_device (id), 
	FOREIGN KEY(channel_id) REFERENCES recorder_channel (id), 
	FOREIGN KEY(factory_id) REFERENCES factory_area (id), 
	FOREIGN KEY(zone_id) REFERENCES factory_zone (id)
);
CREATE INDEX ix_smart_event_binding_id ON smart_event (binding_id);
CREATE INDEX ix_smart_event_camera_id ON smart_event (camera_id);
CREATE INDEX ix_smart_event_camera_time ON smart_event (camera_id, event_time);
CREATE INDEX ix_smart_event_capability_id ON smart_event (capability_id);
CREATE INDEX ix_smart_event_capability_status_time ON smart_event (capability_id, status, event_time);
CREATE INDEX ix_smart_event_channel_id ON smart_event (channel_id);
CREATE INDEX ix_smart_event_channel_time ON smart_event (channel_id, event_time);
CREATE INDEX ix_smart_event_dedup_key ON smart_event (dedup_key);
CREATE INDEX ix_smart_event_dedup_time_id ON smart_event (dedup_key, event_time, id);
CREATE UNIQUE INDEX ix_smart_event_event_code ON smart_event (event_code);
CREATE INDEX ix_smart_event_event_level ON smart_event (event_level);
CREATE INDEX ix_smart_event_event_time ON smart_event (event_time);
CREATE INDEX ix_smart_event_event_type ON smart_event (event_type);
CREATE INDEX ix_smart_event_factory_id ON smart_event (factory_id);
CREATE INDEX ix_smart_event_provider_id ON smart_event (provider_id);
CREATE INDEX ix_smart_event_provider_status_time ON smart_event (provider_id, status, event_time);
CREATE INDEX ix_smart_event_raw_event_id ON smart_event (raw_event_id);
CREATE INDEX ix_smart_event_recorder_id ON smart_event (recorder_id);
CREATE INDEX ix_smart_event_recorder_time ON smart_event (recorder_id, event_time);
CREATE INDEX ix_smart_event_source_stage ON smart_event (source_stage);
CREATE INDEX ix_smart_event_stage_status_time ON smart_event (source_stage, status, event_time);
CREATE INDEX ix_smart_event_status ON smart_event (status);
CREATE INDEX ix_smart_event_zone_id ON smart_event (zone_id);


CREATE TABLE sys_user_role (
	user_id INTEGER NOT NULL, 
	role_id INTEGER NOT NULL, 
	PRIMARY KEY (user_id, role_id), 
	FOREIGN KEY(user_id) REFERENCES sys_user (id), 
	FOREIGN KEY(role_id) REFERENCES sys_role (id)
);


CREATE TABLE ai_review_task (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	smart_event_id INTEGER NOT NULL, 
	task_no VARCHAR(64) NOT NULL, 
	ai_flow_code VARCHAR(60) NOT NULL, 
	model_code VARCHAR(60), 
	request_payload_json TEXT NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	retry_count INTEGER NOT NULL, 
	max_retry_count INTEGER NOT NULL, 
	submitted_at DATETIME NOT NULL, 
	finished_at DATETIME, 
	error_message TEXT, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(smart_event_id) REFERENCES smart_event (id)
);
CREATE INDEX ix_ai_review_task_ai_flow_code ON ai_review_task (ai_flow_code);
CREATE INDEX ix_ai_review_task_model_code ON ai_review_task (model_code);
CREATE INDEX ix_ai_review_task_smart_event_id ON ai_review_task (smart_event_id);
CREATE INDEX ix_ai_review_task_status ON ai_review_task (status);
CREATE INDEX ix_ai_review_task_submitted_at ON ai_review_task (submitted_at);
CREATE UNIQUE INDEX ix_ai_review_task_task_no ON ai_review_task (task_no);


CREATE TABLE ai_review_result (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	task_id INTEGER NOT NULL, 
	decision VARCHAR(20) NOT NULL, 
	labels_json TEXT, 
	confidence FLOAT, 
	reason VARCHAR(255), 
	evidence_json TEXT, 
	result_payload_json TEXT NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(task_id) REFERENCES ai_review_task (id)
);
CREATE INDEX ix_ai_review_result_decision ON ai_review_result (decision);
CREATE INDEX ix_ai_review_result_task_id ON ai_review_result (task_id);


CREATE TABLE alarm_record (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	alarm_no VARCHAR(64) NOT NULL, 
	ai_event_id INTEGER, 
	smart_event_id INTEGER, 
	raw_event_id INTEGER, 
	ai_review_task_id INTEGER, 
	alarm_type VARCHAR(60) NOT NULL, 
	alarm_level VARCHAR(20) NOT NULL, 
	alarm_time DATETIME NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	source_stage VARCHAR(20), 
	parent_alarm_id INTEGER, 
	alarm_origin VARCHAR(40), 
	camera_id INTEGER, 
	recorder_id INTEGER, 
	channel_id INTEGER, 
	factory_id INTEGER, 
	zone_id INTEGER, 
	message VARCHAR(255), 
	image_url VARCHAR(500), 
	video_url VARCHAR(500), 
	record_start_time DATETIME, 
	record_end_time DATETIME, 
	push_records_json TEXT NOT NULL, 
	dedup_key VARCHAR(200) NOT NULL, 
	occurrence_count INTEGER NOT NULL, 
	last_event_time DATETIME, 
	last_push_at DATETIME, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(ai_event_id) REFERENCES ai_event (id), 
	FOREIGN KEY(smart_event_id) REFERENCES smart_event (id), 
	FOREIGN KEY(raw_event_id) REFERENCES smart_raw_event (id), 
	FOREIGN KEY(ai_review_task_id) REFERENCES ai_review_task (id), 
	FOREIGN KEY(parent_alarm_id) REFERENCES alarm_record (id), 
	FOREIGN KEY(camera_id) REFERENCES camera_device (id), 
	FOREIGN KEY(recorder_id) REFERENCES recorder_device (id), 
	FOREIGN KEY(channel_id) REFERENCES recorder_channel (id), 
	FOREIGN KEY(factory_id) REFERENCES factory_area (id), 
	FOREIGN KEY(zone_id) REFERENCES factory_zone (id)
);
CREATE INDEX ix_alarm_record_ai_event_id ON alarm_record (ai_event_id);
CREATE INDEX ix_alarm_record_ai_review_task_id ON alarm_record (ai_review_task_id);
CREATE INDEX ix_alarm_record_alarm_level ON alarm_record (alarm_level);
CREATE UNIQUE INDEX ix_alarm_record_alarm_no ON alarm_record (alarm_no);
CREATE INDEX ix_alarm_record_alarm_origin ON alarm_record (alarm_origin);
CREATE INDEX ix_alarm_record_alarm_time ON alarm_record (alarm_time);
CREATE INDEX ix_alarm_record_alarm_type ON alarm_record (alarm_type);
CREATE INDEX ix_alarm_record_camera_id ON alarm_record (camera_id);
CREATE INDEX ix_alarm_record_channel_id ON alarm_record (channel_id);
CREATE INDEX ix_alarm_record_dedup_key ON alarm_record (dedup_key);
CREATE INDEX ix_alarm_record_dedup_alarm_time_id ON alarm_record (dedup_key, alarm_time, id);
CREATE INDEX ix_alarm_record_dedup_last_event_time_id ON alarm_record (dedup_key, last_event_time, id);
CREATE INDEX ix_alarm_record_factory_id ON alarm_record (factory_id);
CREATE INDEX ix_alarm_record_parent_alarm_id ON alarm_record (parent_alarm_id);
CREATE INDEX ix_alarm_record_raw_event_id ON alarm_record (raw_event_id);
CREATE INDEX ix_alarm_record_recorder_id ON alarm_record (recorder_id);
CREATE INDEX ix_alarm_record_smart_event_id ON alarm_record (smart_event_id);
CREATE INDEX ix_alarm_record_smart_event_id_id ON alarm_record (smart_event_id, id);
CREATE INDEX ix_alarm_record_source_stage ON alarm_record (source_stage);
CREATE INDEX ix_alarm_record_status ON alarm_record (status);
CREATE INDEX ix_alarm_record_zone_id ON alarm_record (zone_id);


CREATE TABLE alarm_process_log (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	alarm_id INTEGER NOT NULL, 
	action VARCHAR(40) NOT NULL, 
	from_status VARCHAR(20), 
	to_status VARCHAR(20), 
	operator_id INTEGER, 
	operator_name VARCHAR(50), 
	remark TEXT, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(alarm_id) REFERENCES alarm_record (id)
);
CREATE INDEX ix_alarm_process_log_action ON alarm_process_log (action);
CREATE INDEX ix_alarm_process_log_alarm_id ON alarm_process_log (alarm_id);


CREATE TABLE alarm_push_log (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	alarm_id INTEGER, 
	push_config_id INTEGER, 
	retry_of_log_id INTEGER, 
	channel VARCHAR(30) NOT NULL, 
	provider_type VARCHAR(30) NOT NULL, 
	status VARCHAR(30) NOT NULL, 
	config_name VARCHAR(100), 
	alarm_no VARCHAR(64), 
	alarm_type VARCHAR(60), 
	alarm_level VARCHAR(20), 
	alarm_dedup_key VARCHAR(200), 
	factory_id INTEGER, 
	zone_id INTEGER, 
	triggered_by VARCHAR(20) NOT NULL, 
	retry_count INTEGER NOT NULL, 
	message TEXT NOT NULL, 
	request_body TEXT, 
	response_body TEXT, 
	error_message TEXT, 
	pushed_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	FOREIGN KEY(alarm_id) REFERENCES alarm_record (id), 
	FOREIGN KEY(push_config_id) REFERENCES push_config (id), 
	FOREIGN KEY(retry_of_log_id) REFERENCES alarm_push_log (id), 
	FOREIGN KEY(factory_id) REFERENCES factory_area (id), 
	FOREIGN KEY(zone_id) REFERENCES factory_zone (id)
);
CREATE INDEX ix_alarm_push_log_alarm_dedup_key ON alarm_push_log (alarm_dedup_key);
CREATE INDEX ix_alarm_push_log_alarm_id ON alarm_push_log (alarm_id);
CREATE INDEX ix_alarm_push_log_alarm_level ON alarm_push_log (alarm_level);
CREATE INDEX ix_alarm_push_log_alarm_no ON alarm_push_log (alarm_no);
CREATE INDEX ix_alarm_push_log_alarm_type ON alarm_push_log (alarm_type);
CREATE INDEX ix_alarm_push_log_channel ON alarm_push_log (channel);
CREATE INDEX ix_alarm_push_log_factory_id ON alarm_push_log (factory_id);
CREATE INDEX ix_alarm_push_log_push_config_id ON alarm_push_log (push_config_id);
CREATE INDEX ix_alarm_push_log_pushed_at ON alarm_push_log (pushed_at);
CREATE INDEX ix_alarm_push_log_retry_of_log_id ON alarm_push_log (retry_of_log_id);
CREATE INDEX ix_alarm_push_log_status ON alarm_push_log (status);
CREATE INDEX ix_alarm_push_log_triggered_by ON alarm_push_log (triggered_by);
CREATE INDEX ix_alarm_push_log_zone_id ON alarm_push_log (zone_id);

-- Seed base master data
INSERT INTO `factory_area` (`id`, `factory_code`, `factory_name`, `status`, `remark`) VALUES (1, 'steel-area-01', '炼钢一区', 'enabled', '系统初始化示例厂区') ON DUPLICATE KEY UPDATE `factory_code` = VALUES(`factory_code`), `factory_name` = VALUES(`factory_name`), `status` = VALUES(`status`), `remark` = VALUES(`remark`);
INSERT INTO `factory_zone` (`id`, `factory_id`, `zone_code`, `zone_name`, `status`, `remark`) VALUES (1, 1, 'converter-platform', '转炉平台', 'enabled', '系统初始化示例区域') ON DUPLICATE KEY UPDATE `factory_id` = VALUES(`factory_id`), `zone_code` = VALUES(`zone_code`), `zone_name` = VALUES(`zone_name`), `status` = VALUES(`status`), `remark` = VALUES(`remark`);
INSERT INTO `sys_dept` (`id`, `dept_code`, `dept_name`, `parent_id`, `factory_id`, `zone_id`, `leader`, `phone`, `sort`, `status`, `remark`) VALUES (1, 'safety-ehs', '安全环保部', NULL, 1, 1, '张工', '13800000000', 1, 'enabled', '系统初始化示例部门') ON DUPLICATE KEY UPDATE `dept_code` = VALUES(`dept_code`), `dept_name` = VALUES(`dept_name`), `parent_id` = VALUES(`parent_id`), `factory_id` = VALUES(`factory_id`), `zone_id` = VALUES(`zone_id`), `leader` = VALUES(`leader`), `phone` = VALUES(`phone`), `sort` = VALUES(`sort`), `status` = VALUES(`status`), `remark` = VALUES(`remark`);
INSERT INTO `sys_dict_type` (`id`, `dict_code`, `dict_name`, `status`, `remark`) VALUES (1, 'alarm_level', '告警等级', 'enabled', '系统初始化示例字典类型') ON DUPLICATE KEY UPDATE `dict_code` = VALUES(`dict_code`), `dict_name` = VALUES(`dict_name`), `status` = VALUES(`status`), `remark` = VALUES(`remark`);
INSERT INTO `sys_dict_item` (`id`, `dict_type_id`, `item_label`, `item_value`, `item_sort`, `is_default`, `status`, `remark`) VALUES (1, 1, '紧急', 'critical', 1, 1, 'enabled', '系统初始化示例字典项') ON DUPLICATE KEY UPDATE `dict_type_id` = VALUES(`dict_type_id`), `item_label` = VALUES(`item_label`), `item_value` = VALUES(`item_value`), `item_sort` = VALUES(`item_sort`), `is_default` = VALUES(`is_default`), `status` = VALUES(`status`), `remark` = VALUES(`remark`);

-- Seed: sys_menu
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (1, '首页驾驶舱', 'dashboard', NULL, 'dashboard', '/dashboard', 'House', 'menu', 1, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (2, '安全日志', 'safety', NULL, NULL, NULL, 'Warning', 'catalog', 2, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (4, '实时告警', 'safety-realtime-alarms', 2, 'safety-realtime-alarms', '/safety/realtime-alarms', 'Bell', 'menu', 2, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (5, '告警查询', 'safety-alarm-list', 2, 'safety-alarm-list', '/safety/alarm-list', 'Warning', 'menu', 3, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (6, '告警统计', 'safety-alarm-stats', 2, 'safety-alarm-stats', '/safety/alarm-stats', 'Histogram', 'menu', 4, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (7, '模块联调', 'linkage', NULL, 'linkage', '/linkage', 'Share', 'menu', 3, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (8, '监控管理', 'monitor', NULL, NULL, NULL, 'Monitor', 'catalog', 4, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (10, '监控预览', 'monitor-preview', 8, 'monitor-preview', '/monitor/preview', 'VideoCamera', 'menu', 2, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (11, '录像查看', 'monitor-playback', 8, 'monitor-playback', '/monitor/playback', 'Operation', 'menu', 3, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (12, '智能接口', 'monitor-ai-api', 8, 'monitor-ai-api', '/monitor/ai-api', 'Connection', 'menu', 4, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (13, '设备管理', 'device', NULL, NULL, NULL, 'Grid', 'catalog', 5, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (14, '摄像机管理', 'device-cameras', 13, 'device-cameras', '/device/cameras', 'VideoCamera', 'menu', 1, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (15, '录像机管理', 'device-recorders', 13, 'device-recorders', '/device/recorders', 'Monitor', 'menu', 2, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (16, '通道管理', 'device-channels', 13, 'device-channels', '/device/channels', 'Connection', 'menu', 3, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (17, '设备日志', 'device-status-logs', 13, 'device-status-logs', '/device/status-logs', 'DataAnalysis', 'menu', 4, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (18, '推送管理', 'push', NULL, NULL, NULL, 'Bell', 'catalog', 6, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (19, '推送配置', 'push-config', 18, 'push-config', '/push/config', 'Setting', 'menu', 1, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (20, '推送日志', 'push-logs', 18, 'push-logs', '/push/logs', 'Files', 'menu', 2, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (21, '基础资料', 'basic-data', NULL, NULL, NULL, 'OfficeBuilding', 'catalog', 7, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (22, '厂区管理', 'basic-data-factories', 21, 'basic-data-factories', '/master-data/factories', 'OfficeBuilding', 'menu', 1, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (23, '区域管理', 'basic-data-zones', 21, 'basic-data-zones', '/master-data/zones', 'Postcard', 'menu', 2, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (24, '部门管理', 'basic-data-depts', 21, 'basic-data-depts', '/master-data/depts', 'User', 'menu', 3, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (25, '字典管理', 'basic-data-dicts', 21, 'basic-data-dicts', '/master-data/dicts', 'Files', 'menu', 4, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (26, '系统管理', 'system', NULL, NULL, NULL, 'Lock', 'catalog', 8, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (27, '用户管理', 'system-users', 26, 'system-users', '/system/users', 'User', 'menu', 1, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (28, '角色权限', 'system-roles', 26, 'system-roles', '/system/roles', 'CircleCheck', 'menu', 2, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);
INSERT INTO `sys_menu` (`id`, `name`, `code`, `parent_id`, `route_name`, `route_path`, `icon`, `menu_type`, `sort`, `status`) VALUES (29, '操作日志', 'safety-operation-logs', 2, 'safety-operation-logs', '/safety/operation-logs', 'Document', 'menu', 5, 'enabled') ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `parent_id` = VALUES(`parent_id`), `route_name` = VALUES(`route_name`), `route_path` = VALUES(`route_path`), `icon` = VALUES(`icon`), `menu_type` = VALUES(`menu_type`), `sort` = VALUES(`sort`), `status` = VALUES(`status`);

-- Seed: sys_permission
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (1, '刷新驾驶舱', 'dashboard:refresh', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (2, '查看摄像机', 'device:camera:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (3, '新增摄像机', 'device:camera:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (4, '编辑摄像机', 'device:camera:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (5, '删除摄像机', 'device:camera:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (6, '测试摄像机连接', 'device:camera:test', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (7, '检测摄像机状态', 'device:camera:check', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (8, '查看录像机', 'device:recorder:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (9, '新增录像机', 'device:recorder:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (10, '编辑录像机', 'device:recorder:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (11, '删除录像机', 'device:recorder:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (12, '测试录像机连接', 'device:recorder:test', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (13, '同步录像机通道', 'device:recorder:sync', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (14, '查看通道', 'device:channel:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (15, '编辑通道', 'device:channel:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (16, '查看设备状态日志', 'device:status:log:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (17, '执行设备全部检测', 'device:status:check', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (18, '查看智能事件', 'ai:event:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (19, '模拟AI回调', 'ai:event:callback', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (20, '查看告警', 'alarm:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (21, '处理告警', 'alarm:process', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (22, '重新推送告警', 'alarm:repush', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (23, '查看推送配置', 'push:config:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (24, '新增推送配置', 'push:config:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (25, '编辑推送配置', 'push:config:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (26, '删除推送配置', 'push:config:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (27, '测试推送配置', 'push:config:test', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (28, '查看推送日志', 'push:log:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (29, '重试推送日志', 'push:log:retry', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (30, '查看厂区', 'basic:factory:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (31, '新增厂区', 'basic:factory:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (32, '编辑厂区', 'basic:factory:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (33, '删除厂区', 'basic:factory:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (34, '查看区域', 'basic:zone:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (35, '新增区域', 'basic:zone:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (36, '编辑区域', 'basic:zone:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (37, '删除区域', 'basic:zone:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (38, '查看部门', 'basic:dept:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (39, '新增部门', 'basic:dept:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (40, '编辑部门', 'basic:dept:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (41, '删除部门', 'basic:dept:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (42, '查看字典', 'basic:dict:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (43, '新增字典', 'basic:dict:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (44, '编辑字典', 'basic:dict:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (45, '删除字典', 'basic:dict:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (46, '查看用户', 'system:user:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (47, '新增用户', 'system:user:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (48, '编辑用户', 'system:user:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (49, '删除用户', 'system:user:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (50, '查看角色', 'system:role:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (51, '新增角色', 'system:role:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (52, '编辑角色', 'system:role:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (53, '删除角色', 'system:role:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (54, '启用角色', 'system:role:enable', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (55, '停用角色', 'system:role:disable', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (56, '查看实时告警', 'alarm:realtime:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (57, '查看驾驶舱统计', 'dashboard:stats:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (58, '查看智能提供方', 'smart:provider:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (59, '新增智能提供方', 'smart:provider:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (60, '编辑智能提供方', 'smart:provider:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (61, '测试智能提供方', 'smart:provider:test', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (62, '查看智能能力', 'smart:capability:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (63, '查看智能绑定', 'smart:binding:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (64, '新增智能绑定', 'smart:binding:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (65, '编辑智能绑定', 'smart:binding:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (66, '删除智能绑定', 'smart:binding:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (67, '测试智能绑定', 'smart:binding:test', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (68, '新增绑定规则', 'smart:rule:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (69, '编辑绑定规则', 'smart:rule:update', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (70, '删除绑定规则', 'smart:rule:delete', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (71, '查看智能事件', 'smart:event:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (72, '查看智能事件详情', 'smart:event:detail:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (73, '提交AI复核任务', 'smart:event:submit-ai-review', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (74, '查看AI任务', 'smart:ai-task:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (75, '重试AI任务', 'smart:ai-task:retry', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (76, '查看实时视频', 'video:live:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (77, '控制实时视频', 'video:live:control', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (78, '查看录像回放', 'video:playback:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (79, '检索录像片段', 'video:playback:search', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (80, '下载录像文件', 'video:playback:download', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (81, '查看WebControl配置', 'video:webcontrol:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (82, '创建抓图任务', 'video:snapshot:create', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (83, '查看告警报表', 'report:alarm:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (84, '导出告警数据', 'report:alarm:export', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (85, '查看设备报表', 'report:device:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (86, '导出设备数据', 'report:device:export', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (87, '查看推送报表', 'report:push:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (88, '导出推送数据', 'report:push:export', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (89, '查看AI事件', 'ai:event:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (90, '接收AI回调', 'ai:event:callback', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (91, '查看操作日志', 'log:operation:view', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);
INSERT INTO `sys_permission` (`id`, `name`, `code`, `status`, `remark`, `is_button`) VALUES (92, '导出操作日志', 'log:operation:export', 'enabled', NULL, 1) ON DUPLICATE KEY UPDATE `name` = VALUES(`name`), `code` = VALUES(`code`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `is_button` = VALUES(`is_button`);

-- Seed: smart_interface_provider
INSERT INTO `smart_interface_provider` (`id`, `provider_code`, `provider_name`, `provider_type`, `auth_type`, `base_url`, `callback_path`, `secret_encrypted`, `config_schema_json`, `enabled`, `remark`) VALUES (1, 'hikvision-sdk', '海康 SDK 报警监听', 'sdk_listener', 'none', NULL, '/smart/events/ingest/hikvision-sdk', NULL, '{"channelNo": {"type": "number", "label": "通道号"}, "armingMode": {"type": "string", "label": "布防模式"}}', 1, '系统初始化提供方') ON DUPLICATE KEY UPDATE `provider_code` = VALUES(`provider_code`), `provider_name` = VALUES(`provider_name`), `provider_type` = VALUES(`provider_type`), `auth_type` = VALUES(`auth_type`), `base_url` = VALUES(`base_url`), `callback_path` = VALUES(`callback_path`), `secret_encrypted` = VALUES(`secret_encrypted`), `config_schema_json` = VALUES(`config_schema_json`), `enabled` = VALUES(`enabled`), `remark` = VALUES(`remark`);
INSERT INTO `smart_interface_provider` (`id`, `provider_code`, `provider_name`, `provider_type`, `auth_type`, `base_url`, `callback_path`, `secret_encrypted`, `config_schema_json`, `enabled`, `remark`) VALUES (3, 'ai-callback', 'AI 回调兼容接入', 'http_callback', 'hmac', NULL, '/ai/events/callback', NULL, '{"signatureHeader": "X-AI-Signature", "payloadMode": "json"}', 1, '兼容现有 AI 事件回调链路') ON DUPLICATE KEY UPDATE `provider_code` = VALUES(`provider_code`), `provider_name` = VALUES(`provider_name`), `provider_type` = VALUES(`provider_type`), `auth_type` = VALUES(`auth_type`), `base_url` = VALUES(`base_url`), `callback_path` = VALUES(`callback_path`), `secret_encrypted` = VALUES(`secret_encrypted`), `config_schema_json` = VALUES(`config_schema_json`), `enabled` = VALUES(`enabled`), `remark` = VALUES(`remark`);

-- Seed: smart_interface_capability
INSERT INTO `smart_interface_capability` (`id`, `capability_code`, `capability_name`, `event_category`, `supports_push`, `supports_pull`, `supports_ai_review`, `payload_schema_json`, `default_rule_json`, `enabled`) VALUES (1, 'motion_detect', '移动侦测', 'security', 1, 0, 1, '{"eventType": "motion_detect"}', '{"alarmLevel": "medium", "sendToAi": true, "generateAlarmDirectly": false, "snapshotEnabled": true}', 1) ON DUPLICATE KEY UPDATE `capability_code` = VALUES(`capability_code`), `capability_name` = VALUES(`capability_name`), `event_category` = VALUES(`event_category`), `supports_push` = VALUES(`supports_push`), `supports_pull` = VALUES(`supports_pull`), `supports_ai_review` = VALUES(`supports_ai_review`), `payload_schema_json` = VALUES(`payload_schema_json`), `default_rule_json` = VALUES(`default_rule_json`), `enabled` = VALUES(`enabled`);
INSERT INTO `smart_interface_capability` (`id`, `capability_code`, `capability_name`, `event_category`, `supports_push`, `supports_pull`, `supports_ai_review`, `payload_schema_json`, `default_rule_json`, `enabled`) VALUES (2, 'ai_analysis', 'AI 分析事件', 'ai', 1, 0, 0, '{"eventType": "helmet_missing"}', '{"alarmLevel": "high", "sendToAi": false, "generateAlarmDirectly": true, "snapshotEnabled": true}', 1) ON DUPLICATE KEY UPDATE `capability_code` = VALUES(`capability_code`), `capability_name` = VALUES(`capability_name`), `event_category` = VALUES(`event_category`), `supports_push` = VALUES(`supports_push`), `supports_pull` = VALUES(`supports_pull`), `supports_ai_review` = VALUES(`supports_ai_review`), `payload_schema_json` = VALUES(`payload_schema_json`), `default_rule_json` = VALUES(`default_rule_json`), `enabled` = VALUES(`enabled`);

-- Seed admin and user roles
INSERT INTO `sys_role` (`id`, `role_code`, `role_name`, `status`, `remark`, `data_scope_type`, `data_scope_value`) VALUES (1, 'admin', '超级管理员', 'enabled', '系统初始化管理员角色', 'all', '*') ON DUPLICATE KEY UPDATE `role_code` = VALUES(`role_code`), `role_name` = VALUES(`role_name`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `data_scope_type` = VALUES(`data_scope_type`), `data_scope_value` = VALUES(`data_scope_value`);
INSERT INTO `sys_role` (`id`, `role_code`, `role_name`, `status`, `remark`, `data_scope_type`, `data_scope_value`) VALUES (2, 'User', '系统操作员', 'enabled', NULL, 'custom', '{"cameraIds":[],"channelIds":[1,2],"deptIds":[1],"factoryIds":[1],"recorderIds":[],"userIds":[],"zoneIds":[1]}') ON DUPLICATE KEY UPDATE `role_code` = VALUES(`role_code`), `role_name` = VALUES(`role_name`), `status` = VALUES(`status`), `remark` = VALUES(`remark`), `data_scope_type` = VALUES(`data_scope_type`), `data_scope_value` = VALUES(`data_scope_value`);
INSERT INTO `sys_user` (`id`, `username`, `password_hash`, `real_name`, `dept_id`, `status`) VALUES (1, 'admin', 'pbkdf2_sha256$120000$80ae8c164153c89f3ecbc837b9fb0246$WSvPE+eBuJzGAsWR1HwWsFJQEf1i5XH5vkS07A9wA8Y=', '系统管理员', 1, 'enabled') ON DUPLICATE KEY UPDATE `username` = VALUES(`username`), `password_hash` = VALUES(`password_hash`), `real_name` = VALUES(`real_name`), `dept_id` = VALUES(`dept_id`), `status` = VALUES(`status`);
INSERT INTO `system_setting` (`id`, `setting_key`, `setting_name`, `setting_value`, `remark`) VALUES (1, 'operation_log_retention_days', '操作日志留存天数', '360', '默认保留 360 天，可按需修改') ON DUPLICATE KEY UPDATE `setting_key` = VALUES(`setting_key`), `setting_name` = VALUES(`setting_name`), `setting_value` = VALUES(`setting_value`), `remark` = VALUES(`remark`);

-- Seed role relations
DELETE FROM `sys_user_role` WHERE `user_id` = 1;
INSERT INTO `sys_user_role` (`user_id`, `role_id`) VALUES (1, 1);
DELETE FROM `sys_role_menu` WHERE `role_id` IN (1, 2);
INSERT INTO `sys_role_menu` (`role_id`, `menu_id`) VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15), (1, 16), (1, 17), (1, 18), (1, 19), (1, 20), (1, 21), (1, 22), (1, 23), (1, 24), (1, 25), (1, 26), (1, 27), (1, 28), (1, 29),
(2, 1), (2, 2), (2, 4), (2, 5), (2, 6), (2, 8), (2, 10), (2, 11), (2, 13), (2, 14), (2, 15), (2, 16), (2, 17), (2, 18), (2, 19), (2, 20), (2, 21), (2, 22), (2, 23), (2, 24), (2, 25);
DELETE FROM `sys_role_permission` WHERE `role_id` IN (1, 2);
INSERT INTO `sys_role_permission` (`role_id`, `permission_id`) VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15), (1, 16), (1, 17), (1, 18), (1, 19), (1, 20), (1, 21), (1, 22), (1, 23), (1, 24), (1, 25), (1, 26), (1, 27), (1, 28), (1, 29), (1, 30), (1, 31), (1, 32), (1, 33), (1, 34), (1, 35), (1, 36), (1, 37), (1, 38), (1, 39), (1, 40), (1, 41), (1, 42), (1, 43), (1, 44), (1, 45), (1, 46), (1, 47), (1, 48), (1, 49), (1, 50), (1, 51), (1, 52), (1, 53), (1, 54), (1, 55), (1, 56), (1, 57), (1, 58), (1, 59), (1, 60), (1, 61), (1, 62), (1, 63), (1, 64), (1, 65), (1, 66), (1, 67), (1, 68), (1, 69), (1, 70), (1, 71), (1, 72), (1, 73), (1, 74), (1, 75), (1, 76), (1, 77), (1, 78), (1, 79), (1, 80), (1, 81), (1, 82), (1, 83), (1, 84), (1, 85), (1, 86), (1, 87), (1, 88), (1, 91), (1, 92),
(2, 1), (2, 2), (2, 6), (2, 7), (2, 8), (2, 14), (2, 16), (2, 17), (2, 20), (2, 21), (2, 22), (2, 23), (2, 28), (2, 30), (2, 34), (2, 38), (2, 42), (2, 56), (2, 57), (2, 76), (2, 77), (2, 78), (2, 79), (2, 80), (2, 81), (2, 82), (2, 83), (2, 84), (2, 85), (2, 87);
